FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["watchmedo", "auto-restart", "--recursive", "--pattern=*.py", "--", "celery", "-A", "app.workers.celery_app.celery_app", "worker", "--loglevel=info", "-Q", "city_queue"]

